[log]
level = "warn"
output = "realm.log"

[network]
no_tcp = false
use_udp = true

[[endpoints]]
listen = "0.0.0.0:1001"
remote = "114.114.114.114:443"

[[endpoints]]
listen = "0.0.0.0:1002"
remote = "www.google.com:443"